### ISSUE TITLE
[BUG] Creating a VNET jail ignores template from thin or thick

### ISSUE THREAD

**Issue by michael-o** [BastilleBSD/bastille#401]
**[MANDATORY] Describe the bug [MANDATORY]**
When you create a jail with `-T  -V` `THICK_JAIL` and `VNET_JAIL` is set, but the template for think jails or if absent thin jails is never run.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.8.20210115
12.2-STABLE
12.2-STABLE
12.2-STABLE

**[MANDATORY] How did you install bastille? (port/pkg/git)**
ports

**[optional] Steps to reproduce?**
Add `CMD` to thick or thin `Bastillefile` and create a VNET jail. Those commands are ignored.

**[optional] Expected behavior**
My expectation is that VNET jails are a layer on top of thin or thick jails and not on the side becaue the network does not affect how the jail is created.

**[optional]  Additional context**

I want to add this to `think/Bastillefile` when creating both:
```
CMD rm -f /.cshrc /.profile /root/.cshrc /root/.login /root/.hushlogin /root/.profile /etc/csh.* /etc/profile /usr/share/skel/*
```
But fiddling with `/usr/share/skel` only works on thick jails.
Some magic needs to be added here:
https://github.com/BastilleBSD/bastille/blob/b85d6347dee44c943819c2d7b4eee9c5a30535b5/usr/local/share/bastille/create.sh#L396-L397

**Comment by cedwards** [comment]
This has been a limitation of Bastille that was addressed in #638 . Now, when you create you can specify a combination of options, eg; `-TV|-VT` for a "thick" jail with VNET. When options are combined, both sets of templates should be applied.

Note: I'd recommend using `-CV|-VC` for ZFS Clone with VNET on ZFS enabled systems. This method uses even less storage than "thick" or "thin" methods.

**Comment by michael-o** [comment]
> Note: I'd recommend using `-CV|-VC` for ZFS Clone with VNET on ZFS enabled systems. This method uses even less storage than "thick" or "thin" methods.

True, but this pins the parent snapshot to this specific jail unless one promotes the dataset. That should be mentioned somewhere in the docs.

**Comment by michael-o** [comment]
This one needs to be reopened. It is not fixed.
The application of th templates are not cumulated regardless of the flags provided:
https://github.com/BastilleBSD/bastille/blob/3a4ebc63bb84b66d456713e608be86e4cba3b637/usr/local/share/bastille/create.sh#L501-L573. Line 548 should be drop `elif` to `fi if`.

**Comment by michael-o** [comment]
@cedwards or @bmac2, please reopen.

**Comment by michael-o** [comment]
@yaazkal Can you reopen, please?

**Comment by michael-o** [comment]
@bmac2 Can you reopen for re-evaluation?

**Comment by tschettervictor** [comment]
@michael-o 

Can you test #843
